### ISSUE TITLE
How to set timeout on a redis cluster client

### ISSUE THREAD

**Issue by wangfuqiang** [Nordix/hiredis-cluster#83]
Does hiredis-cluster fix this bug？

hiredis-vip : master
date : 2019-11-25
hiredis version in hircluster.h : 1.0.0

In my code, I got a redisClusterContext,
I called
struct timeval tv = { _timeout_ms / 1000, (_timeout_ms % 1000) * 1000};
_context = redisClusterConnectWithTimeout(_host.c_str(), tv, HIRCLUSTER_FLAG_NULL);
if (redisClusterSetOptionTimeout(_context,tv) != REDIS_OK) { /* log on error */ }

Why it won't work, if I set _timeout_ms=10 , my redis command timer still get a number bigger than 10, say 29 maybe...

**Comment by bjosv** [comment]
I'm not sure that I understand what you are running when you get this problem.
`vipshop/hiredis-vip` had its own version of `hiredis` baked-in, and think it was using hiredis-0.13.1 as a base.
That version of `hiredis` might have had problems with the command timeout, see https://github.com/redis/hiredis/pull/839.

If you use `hiredis-cluster` with `hiredis` >= v1.0.0 I believe it works as expected.

**Comment by wangfuqiang** [comment]
thx for your apply， i will vefiry it

**Comment by wangfuqiang** [comment]
> thx for your apply， i will vefiry it

**Comment by wangfuqiang** [comment]
> I'm not sure that I understand what you are running when you get this problem. `vipshop/hiredis-vip` had its own version of `hiredis` baked-in, and I believe it was using hiredis-0.13.1 as a base. That version of `hiredis` might have had problems with the command timeout, see [redis/hiredis#839](https://github.com/redis/hiredis/pull/839).
> 
> If you use `hiredis-cluster` with `hiredis` >= v1.0.0 I believe it works as expected.

Bad news；
it does not work;
hiredis-cluster master
code:
struct timeval tv = { 0, 2000};
redisClusterSetOptionTimeout(handle_, tv) != REDIS_OK

**Comment by bjosv** [comment]
I have created some tests and verified what you have seen. There are issues in hiredis-cluster that will be fixed when #84 is merged.

**Comment by bjosv** [comment]
Ok, I have not verified the exact timing of it, since it is hiredis that handles it.
The problem found in hiredis-cluster was that the config was not even given to hiredis.
I have only tested that a lack of a response from a server makes sure that a rdisClusterCommand breaks.

I would guess that the precision of timing depends of hardware or if there are context switches.
hiredis set the `SO_RCVTIMEO` and `SO_SNDTIMEO` socketoptions to tell the kernel to respond with an error after given time (see [link](https://linux.die.net/man/7/socket)).

Are you running Linux? and what kind of numbers do you get when setting 5ms?

**Comment by wangfuqiang** [comment]
Are you running Linux? and what kind of numbers do you get when setting 5ms?
yes, we are running the service on linux,  It may gets a repply beyond  20ms where setting 5ms

**Comment by bjosv** [comment]
I ran some tests myself and the precision is not perfect.
Since hiredis-cluster rely on hiredis, and hiredis relies on a socket config, i.e the kernel,  I'm not sure how we could improve this.
We are not running on a real-time system, so I would guess we couldn't get an exact precision.
I'm open to proposals or ideas how to improve it.

Configured timeout vs result of 500 queries (Linux x86_64 5.4.0-122-generic):
```
Conf:   Result:
1ms   - Average:    8 ms  Max:   12 ms  Min:    6 ms
5ms   - Average:   12 ms  Max:   16 ms  Min:    8 ms
10ms  - Average:   16 ms  Max:   20 ms  Min:   14 ms
20ms  - Average:   24 ms  Max:   30 ms  Min:   23 ms
50ms  - Average:   56 ms  Max:   60 ms  Min:   52 ms
100ms - Average:  104 ms  Max:  108 ms  Min:  103 ms
500ms - Average:  511 ms  Max:  516 ms  Min:  507 ms
1s    - Average: 1023 ms  Max: 1028 ms  Min: 1009 ms
```

I will verify that we get the same results with hiredis only.
